services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "9999:8080"

  nginx:
    image: nginx:1.27-alpine
    container_name: dev-nginx
    ports:
      - "8080:80"
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # Needed on Linux so the container can reach services on the host
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: node:lts-alpine3.22
    container_name: dev-frontend
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host --port 5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  frontend_node_modules: